export type Match = { fase: string; adversario: string; resultado: string };
export type Team = {
  nome: string;
  bandeira: string;
  jogos: number;
  vitorias: number;
  empates: number;
  derrotas: number;
  golsPro: number;
  golsContra: number;
  trajetoria: Match[];
};
export type Cup = {
  ano: number;
  sede: string;
  sedeBandeira: string;
  campeao: Team;
  vice: Team;
  artilheiro?: string;
  melhorJogador?: string;
  melhorGoleiro?: string;
  mascote?: string;
  curiosidades: string[];
};

export const cups: Cup[] = [
  {
    ano: 1930, sede: "Uruguai", sedeBandeira: "🇺🇾",
    artilheiro: "Guillermo Stábile (Argentina) – 8 gols",
    campeao: { nome: "Uruguai", bandeira: "🇺🇾", jogos: 4, vitorias: 4, empates: 0, derrotas: 0, golsPro: 15, golsContra: 3, trajetoria: [
      { fase: "Grupo", adversario: "Peru", resultado: "1 x 0" },
      { fase: "Grupo", adversario: "Romênia", resultado: "4 x 0" },
      { fase: "Semifinal", adversario: "Iugoslávia", resultado: "6 x 1" },
      { fase: "Final", adversario: "Argentina", resultado: "4 x 2" },
    ]},
    vice: { nome: "Argentina", bandeira: "🇦🇷", jogos: 4, vitorias: 3, empates: 0, derrotas: 1, golsPro: 12, golsContra: 8, trajetoria: [
      { fase: "Grupo", adversario: "França", resultado: "1 x 0" },
      { fase: "Grupo", adversario: "México", resultado: "6 x 3" },
      { fase: "Grupo", adversario: "Chile", resultado: "3 x 1" },
      { fase: "Final", adversario: "Uruguai", resultado: "2 x 4" },
    ]},
    curiosidades: ["Primeira Copa do Mundo da história", "Uruguai campeão invicto", "Não houve eliminatórias"],
  },
  {
    ano: 1934, sede: "Itália", sedeBandeira: "🇮🇹",
    artilheiro: "Oldřich Nejedlý (Tchecoslováquia) – 5 gols",
    campeao: { nome: "Itália", bandeira: "🇮🇹", jogos: 5, vitorias: 4, empates: 1, derrotas: 0, golsPro: 12, golsContra: 3, trajetoria: [
      { fase: "Oitavas", adversario: "Estados Unidos", resultado: "7 x 1" },
      { fase: "Quartas", adversario: "Espanha", resultado: "1 x 1" },
      { fase: "Replay", adversario: "Espanha", resultado: "1 x 0" },
      { fase: "Semifinal", adversario: "Áustria", resultado: "1 x 0" },
      { fase: "Final", adversario: "Tchecoslováquia", resultado: "2 x 1" },
    ]},
    vice: { nome: "Tchecoslováquia", bandeira: "🇨🇿", jogos: 4, vitorias: 3, empates: 0, derrotas: 1, golsPro: 9, golsContra: 6, trajetoria: [
      { fase: "Oitavas", adversario: "Romênia", resultado: "2 x 1" },
      { fase: "Quartas", adversario: "Suíça", resultado: "3 x 2" },
      { fase: "Semifinal", adversario: "Alemanha", resultado: "3 x 1" },
      { fase: "Final", adversario: "Itália", resultado: "1 x 2" },
    ]},
    curiosidades: ["Final decidida na prorrogação", "Forte influência política do país sede"],
  },
  {
    ano: 1938, sede: "França", sedeBandeira: "🇫🇷",
    artilheiro: "Leônidas (Brasil) – 7 gols",
    campeao: { nome: "Itália", bandeira: "🇮🇹", jogos: 4, vitorias: 4, empates: 0, derrotas: 0, golsPro: 11, golsContra: 5, trajetoria: [
      { fase: "Oitavas", adversario: "Noruega", resultado: "2 x 1" },
      { fase: "Quartas", adversario: "França", resultado: "3 x 1" },
      { fase: "Semifinal", adversario: "Brasil", resultado: "2 x 1" },
      { fase: "Final", adversario: "Hungria", resultado: "4 x 2" },
    ]},
    vice: { nome: "Hungria", bandeira: "🇭🇺", jogos: 4, vitorias: 3, empates: 0, derrotas: 1, golsPro: 15, golsContra: 5, trajetoria: [
      { fase: "Oitavas", adversario: "Índias Orientais Holandesas", resultado: "6 x 0" },
      { fase: "Quartas", adversario: "Suíça", resultado: "2 x 0" },
      { fase: "Semifinal", adversario: "Suécia", resultado: "5 x 1" },
      { fase: "Final", adversario: "Itália", resultado: "2 x 4" },
    ]},
    curiosidades: ["Itália se tornou o primeiro bicampeão mundial", "Itália eliminou o Brasil na semifinal"],
  },
  {
    ano: 1950, sede: "Brasil", sedeBandeira: "🇧🇷",
    campeao: { nome: "Uruguai", bandeira: "🇺🇾", jogos: 4, vitorias: 3, empates: 1, derrotas: 0, golsPro: 0, golsContra: 0, trajetoria: [
      { fase: "Grupo", adversario: "Bolívia", resultado: "8 x 0" },
      { fase: "Fase Final", adversario: "Espanha", resultado: "2 x 2" },
      { fase: "Fase Final", adversario: "Suécia", resultado: "3 x 2" },
      { fase: "Fase Final", adversario: "Brasil", resultado: "2 x 1" },
    ]},
    vice: { nome: "Brasil", bandeira: "🇧🇷", jogos: 6, vitorias: 4, empates: 1, derrotas: 1, golsPro: 0, golsContra: 0, trajetoria: [
      { fase: "Grupo", adversario: "México", resultado: "4 x 0" },
      { fase: "Grupo", adversario: "Suíça", resultado: "2 x 2" },
      { fase: "Grupo", adversario: "Iugoslávia", resultado: "2 x 0" },
      { fase: "Fase Final", adversario: "Suécia", resultado: "7 x 1" },
      { fase: "Fase Final", adversario: "Espanha", resultado: "6 x 1" },
      { fase: "Fase Final", adversario: "Uruguai", resultado: "1 x 2" },
    ]},
    curiosidades: ["O famoso 'Maracanazo'", "Maior público da história do futebol (~199.854)"],
  },
  {
    ano: 1954, sede: "Suíça", sedeBandeira: "🇨🇭",
    artilheiro: "Sándor Kocsis (Hungria) – 11 gols",
    campeao: { nome: "Alemanha Ocidental", bandeira: "🇩🇪", jogos: 6, vitorias: 5, empates: 0, derrotas: 1, golsPro: 25, golsContra: 14, trajetoria: [
      { fase: "Grupo", adversario: "Turquia", resultado: "4 x 1" },
      { fase: "Grupo", adversario: "Hungria", resultado: "3 x 8" },
      { fase: "Desempate", adversario: "Turquia", resultado: "7 x 2" },
      { fase: "Quartas", adversario: "Iugoslávia", resultado: "2 x 0" },
      { fase: "Semifinal", adversario: "Áustria", resultado: "6 x 1" },
      { fase: "Final", adversario: "Hungria", resultado: "3 x 2" },
    ]},
    vice: { nome: "Hungria", bandeira: "🇭🇺", jogos: 5, vitorias: 4, empates: 0, derrotas: 1, golsPro: 27, golsContra: 10, trajetoria: [
      { fase: "Grupo", adversario: "Coreia do Sul", resultado: "9 x 0" },
      { fase: "Grupo", adversario: "Alemanha Ocidental", resultado: "8 x 3" },
      { fase: "Quartas", adversario: "Brasil", resultado: "4 x 2" },
      { fase: "Semifinal", adversario: "Uruguai", resultado: "4 x 2 (prorrog.)" },
      { fase: "Final", adversario: "Alemanha Ocidental", resultado: "2 x 3" },
    ]},
    curiosidades: ["'Milagre de Berna'", "Hungria chegou invicta à final"],
  },
  {
    ano: 1958, sede: "Suécia", sedeBandeira: "🇸🇪",
    artilheiro: "Just Fontaine (França) – 13 gols (recorde em uma Copa)",
    campeao: { nome: "Brasil", bandeira: "🇧🇷", jogos: 6, vitorias: 5, empates: 1, derrotas: 0, golsPro: 16, golsContra: 4, trajetoria: [
      { fase: "Grupo", adversario: "Áustria", resultado: "3 x 0" },
      { fase: "Grupo", adversario: "Inglaterra", resultado: "0 x 0" },
      { fase: "Grupo", adversario: "União Soviética", resultado: "2 x 0" },
      { fase: "Quartas", adversario: "País de Gales", resultado: "1 x 0" },
      { fase: "Semifinal", adversario: "França", resultado: "5 x 2" },
      { fase: "Final", adversario: "Suécia", resultado: "5 x 2" },
    ]},
    vice: { nome: "Suécia", bandeira: "🇸🇪", jogos: 6, vitorias: 4, empates: 1, derrotas: 1, golsPro: 12, golsContra: 9, trajetoria: [
      { fase: "Grupo", adversario: "México", resultado: "3 x 0" },
      { fase: "Grupo", adversario: "Hungria", resultado: "2 x 1" },
      { fase: "Grupo", adversario: "País de Gales", resultado: "0 x 0" },
      { fase: "Quartas", adversario: "União Soviética", resultado: "2 x 0" },
      { fase: "Semifinal", adversario: "Alemanha Ocidental", resultado: "3 x 1" },
      { fase: "Final", adversario: "Brasil", resultado: "2 x 5" },
    ]},
    curiosidades: ["Pelé, com 17 anos, marcou 2 gols na final", "Primeiro título mundial brasileiro"],
  },
  {
    ano: 1962, sede: "Chile", sedeBandeira: "🇨🇱",
    campeao: { nome: "Brasil", bandeira: "🇧🇷", jogos: 6, vitorias: 5, empates: 1, derrotas: 0, golsPro: 14, golsContra: 5, trajetoria: [
      { fase: "Grupo", adversario: "México", resultado: "2 x 0" },
      { fase: "Grupo", adversario: "Tchecoslováquia", resultado: "0 x 0" },
      { fase: "Grupo", adversario: "Espanha", resultado: "2 x 1" },
      { fase: "Quartas", adversario: "Inglaterra", resultado: "3 x 1" },
      { fase: "Semifinal", adversario: "Chile", resultado: "4 x 2" },
      { fase: "Final", adversario: "Tchecoslováquia", resultado: "3 x 1" },
    ]},
    vice: { nome: "Tchecoslováquia", bandeira: "🇨🇿", jogos: 6, vitorias: 4, empates: 1, derrotas: 1, golsPro: 9, golsContra: 5, trajetoria: [
      { fase: "Grupo", adversario: "Espanha", resultado: "1 x 0" },
      { fase: "Grupo", adversario: "Brasil", resultado: "0 x 0" },
      { fase: "Grupo", adversario: "México", resultado: "3 x 1" },
      { fase: "Quartas", adversario: "Hungria", resultado: "1 x 0" },
      { fase: "Semifinal", adversario: "Iugoslávia", resultado: "3 x 1" },
      { fase: "Final", adversario: "Brasil", resultado: "1 x 3" },
    ]},
    curiosidades: ["Pelé lesionou-se cedo", "Garrincha foi a grande estrela"],
  },
  {
    ano: 1966, sede: "Inglaterra", sedeBandeira: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    artilheiro: "Eusébio (Portugal) – 9 gols",
    campeao: { nome: "Inglaterra", bandeira: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", jogos: 6, vitorias: 5, empates: 1, derrotas: 0, golsPro: 11, golsContra: 3, trajetoria: [
      { fase: "Grupo", adversario: "Uruguai", resultado: "0 x 0" },
      { fase: "Grupo", adversario: "México", resultado: "2 x 0" },
      { fase: "Grupo", adversario: "França", resultado: "2 x 0" },
      { fase: "Quartas", adversario: "Argentina", resultado: "1 x 0" },
      { fase: "Semifinal", adversario: "Portugal", resultado: "2 x 1" },
      { fase: "Final", adversario: "Alemanha Ocidental", resultado: "4 x 2 (prorrog.)" },
    ]},
    vice: { nome: "Alemanha Ocidental", bandeira: "🇩🇪", jogos: 6, vitorias: 4, empates: 1, derrotas: 1, golsPro: 15, golsContra: 6, trajetoria: [
      { fase: "Grupo", adversario: "Suíça", resultado: "5 x 0" },
      { fase: "Grupo", adversario: "Argentina", resultado: "0 x 0" },
      { fase: "Grupo", adversario: "Espanha", resultado: "2 x 1" },
      { fase: "Quartas", adversario: "Uruguai", resultado: "4 x 0" },
      { fase: "Semifinal", adversario: "União Soviética", resultado: "2 x 1" },
      { fase: "Final", adversario: "Inglaterra", resultado: "2 x 4 (prorrog.)" },
    ]},
    mascote: "Willie",
    curiosidades: ["Único título da Inglaterra", "Gol fantasma de Geoff Hurst gerou polêmica"],
  },
  {
    ano: 1970, sede: "México", sedeBandeira: "🇲🇽",
    artilheiro: "Gerd Müller (Alemanha Ocidental) – 10 gols",
    campeao: { nome: "Brasil", bandeira: "🇧🇷", jogos: 6, vitorias: 6, empates: 0, derrotas: 0, golsPro: 19, golsContra: 7, trajetoria: [
      { fase: "Grupo", adversario: "Tchecoslováquia", resultado: "4 x 1" },
      { fase: "Grupo", adversario: "Inglaterra", resultado: "1 x 0" },
      { fase: "Grupo", adversario: "Romênia", resultado: "3 x 2" },
      { fase: "Quartas", adversario: "Peru", resultado: "4 x 2" },
      { fase: "Semifinal", adversario: "Uruguai", resultado: "3 x 1" },
      { fase: "Final", adversario: "Itália", resultado: "4 x 1" },
    ]},
    vice: { nome: "Itália", bandeira: "🇮🇹", jogos: 6, vitorias: 3, empates: 2, derrotas: 1, golsPro: 10, golsContra: 8, trajetoria: [
      { fase: "Grupo", adversario: "Suécia", resultado: "1 x 0" },
      { fase: "Grupo", adversario: "Uruguai", resultado: "0 x 0" },
      { fase: "Grupo", adversario: "Israel", resultado: "0 x 0" },
      { fase: "Quartas", adversario: "México", resultado: "4 x 1" },
      { fase: "Semifinal", adversario: "Alemanha Ocidental", resultado: "4 x 3 (prorrog.)" },
      { fase: "Final", adversario: "Brasil", resultado: "1 x 4" },
    ]},
    mascote: "Juanito",
    curiosidades: ["Brasil campeão com 100% de aproveitamento", "Tri brasileiro — a Taça Jules Rimet foi conquistada definitivamente"],
  },
  {
    ano: 1974, sede: "Alemanha Ocidental", sedeBandeira: "🇩🇪",
    artilheiro: "Grzegorz Lato (Polônia) – 7 gols",
    campeao: { nome: "Alemanha Ocidental", bandeira: "🇩🇪", jogos: 7, vitorias: 6, empates: 0, derrotas: 1, golsPro: 13, golsContra: 4, trajetoria: [
      { fase: "Grupo", adversario: "Chile", resultado: "1 x 0" },
      { fase: "Grupo", adversario: "Austrália", resultado: "3 x 0" },
      { fase: "Grupo", adversario: "Alemanha Oriental", resultado: "0 x 1" },
      { fase: "2ª Fase", adversario: "Iugoslávia", resultado: "2 x 0" },
      { fase: "2ª Fase", adversario: "Suécia", resultado: "4 x 2" },
      { fase: "2ª Fase", adversario: "Polônia", resultado: "1 x 0" },
      { fase: "Final", adversario: "Holanda", resultado: "2 x 1" },
    ]},
    vice: { nome: "Holanda", bandeira: "🇳🇱", jogos: 7, vitorias: 5, empates: 1, derrotas: 1, golsPro: 15, golsContra: 3, trajetoria: [
      { fase: "Grupo", adversario: "Uruguai", resultado: "2 x 0" },
      { fase: "Grupo", adversario: "Suécia", resultado: "0 x 0" },
      { fase: "Grupo", adversario: "Bulgária", resultado: "4 x 1" },
      { fase: "2ª Fase", adversario: "Argentina", resultado: "4 x 0" },
      { fase: "2ª Fase", adversario: "Alemanha Oriental", resultado: "2 x 0" },
      { fase: "2ª Fase", adversario: "Brasil", resultado: "2 x 0" },
      { fase: "Final", adversario: "Alemanha Ocidental", resultado: "1 x 2" },
    ]},
    mascote: "Tip e Tap",
    curiosidades: ["'Carrossel Holandês' de Cruyff", "Estreia da nova Taça FIFA"],
  },
  {
    ano: 1978, sede: "Argentina", sedeBandeira: "🇦🇷",
    artilheiro: "Mario Kempes (Argentina) – 6 gols",
    campeao: { nome: "Argentina", bandeira: "🇦🇷", jogos: 7, vitorias: 5, empates: 1, derrotas: 1, golsPro: 15, golsContra: 4, trajetoria: [
      { fase: "Grupo", adversario: "Hungria", resultado: "2 x 1" },
      { fase: "Grupo", adversario: "França", resultado: "2 x 1" },
      { fase: "Grupo", adversario: "Itália", resultado: "0 x 1" },
      { fase: "2ª Fase", adversario: "Polônia", resultado: "2 x 0" },
      { fase: "2ª Fase", adversario: "Brasil", resultado: "0 x 0" },
      { fase: "2ª Fase", adversario: "Peru", resultado: "6 x 0" },
      { fase: "Final", adversario: "Holanda", resultado: "3 x 1 (prorrog.)" },
    ]},
    vice: { nome: "Holanda", bandeira: "🇳🇱", jogos: 7, vitorias: 4, empates: 2, derrotas: 1, golsPro: 16, golsContra: 9, trajetoria: [
      { fase: "Grupo", adversario: "Irã", resultado: "3 x 0" },
      { fase: "Grupo", adversario: "Peru", resultado: "0 x 0" },
      { fase: "Grupo", adversario: "Escócia", resultado: "3 x 2" },
      { fase: "2ª Fase", adversario: "Áustria", resultado: "5 x 1" },
      { fase: "2ª Fase", adversario: "Alemanha Ocidental", resultado: "2 x 2" },
      { fase: "2ª Fase", adversario: "Itália", resultado: "2 x 1" },
      { fase: "Final", adversario: "Argentina", resultado: "1 x 3 (prorrog.)" },
    ]},
    mascote: "Gauchito",
    curiosidades: ["Primeiro título argentino", "Holanda perdeu duas finais seguidas"],
  },
  {
    ano: 1982, sede: "Espanha", sedeBandeira: "🇪🇸",
    artilheiro: "Paolo Rossi (Itália) – 6 gols",
    campeao: { nome: "Itália", bandeira: "🇮🇹", jogos: 7, vitorias: 4, empates: 3, derrotas: 0, golsPro: 12, golsContra: 6, trajetoria: [
      { fase: "Grupo", adversario: "Polônia", resultado: "0 x 0" },
      { fase: "Grupo", adversario: "Peru", resultado: "1 x 1" },
      { fase: "Grupo", adversario: "Camarões", resultado: "1 x 1" },
      { fase: "2ª Fase", adversario: "Argentina", resultado: "2 x 1" },
      { fase: "2ª Fase", adversario: "Brasil", resultado: "3 x 2" },
      { fase: "Semifinal", adversario: "Polônia", resultado: "2 x 0" },
      { fase: "Final", adversario: "Alemanha Ocidental", resultado: "3 x 1" },
    ]},
    vice: { nome: "Alemanha Ocidental", bandeira: "🇩🇪", jogos: 7, vitorias: 4, empates: 2, derrotas: 1, golsPro: 14, golsContra: 11, trajetoria: [
      { fase: "Grupo", adversario: "Argélia", resultado: "1 x 2" },
      { fase: "Grupo", adversario: "Chile", resultado: "4 x 1" },
      { fase: "Grupo", adversario: "Áustria", resultado: "1 x 0" },
      { fase: "2ª Fase", adversario: "Inglaterra", resultado: "0 x 0" },
      { fase: "2ª Fase", adversario: "Espanha", resultado: "2 x 1" },
      { fase: "Semifinal", adversario: "França", resultado: "3 x 3 (5x4 pên.)" },
      { fase: "Final", adversario: "Itália", resultado: "1 x 3" },
    ]},
    mascote: "Naranjito",
    curiosidades: ["Itália eliminou o Brasil em jogo histórico", "Paolo Rossi: artilheiro decisivo"],
  },
  {
    ano: 1986, sede: "México", sedeBandeira: "🇲🇽",
    artilheiro: "Gary Lineker (Inglaterra) – 6 gols",
    campeao: { nome: "Argentina", bandeira: "🇦🇷", jogos: 7, vitorias: 6, empates: 1, derrotas: 0, golsPro: 14, golsContra: 5, trajetoria: [
      { fase: "Grupo", adversario: "Coreia do Sul", resultado: "3 x 1" },
      { fase: "Grupo", adversario: "Itália", resultado: "1 x 1" },
      { fase: "Grupo", adversario: "Bulgária", resultado: "2 x 0" },
      { fase: "Oitavas", adversario: "Uruguai", resultado: "1 x 0" },
      { fase: "Quartas", adversario: "Inglaterra", resultado: "2 x 1" },
      { fase: "Semifinal", adversario: "Bélgica", resultado: "2 x 0" },
      { fase: "Final", adversario: "Alemanha Ocidental", resultado: "3 x 2" },
    ]},
    vice: { nome: "Alemanha Ocidental", bandeira: "🇩🇪", jogos: 7, vitorias: 4, empates: 2, derrotas: 1, golsPro: 8, golsContra: 7, trajetoria: [
      { fase: "Grupo", adversario: "Uruguai", resultado: "1 x 1" },
      { fase: "Grupo", adversario: "Escócia", resultado: "2 x 1" },
      { fase: "Grupo", adversario: "Dinamarca", resultado: "0 x 2" },
      { fase: "Oitavas", adversario: "Marrocos", resultado: "1 x 0" },
      { fase: "Quartas", adversario: "México", resultado: "0 x 0 (4x1 pên.)" },
      { fase: "Semifinal", adversario: "França", resultado: "2 x 0" },
      { fase: "Final", adversario: "Argentina", resultado: "2 x 3" },
    ]},
    mascote: "Pique",
    curiosidades: ["'Gol do Século' de Maradona contra Inglaterra", "'La mano de Dios'"],
  },
  {
    ano: 1990, sede: "Itália", sedeBandeira: "🇮🇹",
    artilheiro: "Salvatore Schillaci (Itália) – 6 gols",
    campeao: { nome: "Alemanha Ocidental", bandeira: "🇩🇪", jogos: 7, vitorias: 5, empates: 2, derrotas: 0, golsPro: 15, golsContra: 5, trajetoria: [
      { fase: "Grupo", adversario: "Iugoslávia", resultado: "4 x 1" },
      { fase: "Grupo", adversario: "Emirados Árabes", resultado: "5 x 1" },
      { fase: "Grupo", adversario: "Colômbia", resultado: "1 x 1" },
      { fase: "Oitavas", adversario: "Holanda", resultado: "2 x 1" },
      { fase: "Quartas", adversario: "Tchecoslováquia", resultado: "1 x 0" },
      { fase: "Semifinal", adversario: "Inglaterra", resultado: "1 x 1 (4x3 pên.)" },
      { fase: "Final", adversario: "Argentina", resultado: "1 x 0" },
    ]},
    vice: { nome: "Argentina", bandeira: "🇦🇷", jogos: 7, vitorias: 3, empates: 3, derrotas: 1, golsPro: 5, golsContra: 4, trajetoria: [
      { fase: "Grupo", adversario: "Camarões", resultado: "0 x 1" },
      { fase: "Grupo", adversario: "União Soviética", resultado: "2 x 0" },
      { fase: "Grupo", adversario: "Romênia", resultado: "1 x 1" },
      { fase: "Oitavas", adversario: "Brasil", resultado: "1 x 0" },
      { fase: "Quartas", adversario: "Iugoslávia", resultado: "0 x 0 (3x2 pên.)" },
      { fase: "Semifinal", adversario: "Itália", resultado: "1 x 1 (4x3 pên.)" },
      { fase: "Final", adversario: "Alemanha Ocidental", resultado: "0 x 1" },
    ]},
    mascote: "Ciao",
    curiosidades: ["Final com menos gols da era moderna", "Camarões surpreendeu na estreia"],
  },
  {
    ano: 1994, sede: "Estados Unidos", sedeBandeira: "🇺🇸",
    artilheiro: "Oleg Salenko (RUS) e Hristo Stoichkov (BUL) – 6 gols",
    campeao: { nome: "Brasil", bandeira: "🇧🇷", jogos: 7, vitorias: 5, empates: 2, derrotas: 0, golsPro: 11, golsContra: 3, trajetoria: [
      { fase: "Grupo", adversario: "Rússia", resultado: "2 x 0" },
      { fase: "Grupo", adversario: "Camarões", resultado: "3 x 0" },
      { fase: "Grupo", adversario: "Suécia", resultado: "1 x 1" },
      { fase: "Oitavas", adversario: "Estados Unidos", resultado: "1 x 0" },
      { fase: "Quartas", adversario: "Holanda", resultado: "3 x 2" },
      { fase: "Semifinal", adversario: "Suécia", resultado: "1 x 0" },
      { fase: "Final", adversario: "Itália", resultado: "0 x 0 (3x2 pên.)" },
    ]},
    vice: { nome: "Itália", bandeira: "🇮🇹", jogos: 7, vitorias: 4, empates: 2, derrotas: 1, golsPro: 8, golsContra: 5, trajetoria: [
      { fase: "Grupo", adversario: "Irlanda", resultado: "0 x 1" },
      { fase: "Grupo", adversario: "Noruega", resultado: "1 x 0" },
      { fase: "Grupo", adversario: "México", resultado: "1 x 1" },
      { fase: "Oitavas", adversario: "Nigéria", resultado: "2 x 1 (prorrog.)" },
      { fase: "Quartas", adversario: "Espanha", resultado: "2 x 1" },
      { fase: "Semifinal", adversario: "Bulgária", resultado: "2 x 1" },
      { fase: "Final", adversario: "Brasil", resultado: "0 x 0 (2x3 pên.)" },
    ]},
    mascote: "Striker",
    curiosidades: ["Tetra brasileiro decidido nos pênaltis", "Roberto Baggio perdeu o pênalti decisivo"],
  },
  {
    ano: 1998, sede: "França", sedeBandeira: "🇫🇷",
    artilheiro: "Davor Šuker (Croácia) – 6 gols",
    campeao: { nome: "França", bandeira: "🇫🇷", jogos: 7, vitorias: 6, empates: 1, derrotas: 0, golsPro: 15, golsContra: 2, trajetoria: [
      { fase: "Grupo", adversario: "África do Sul", resultado: "3 x 0" },
      { fase: "Grupo", adversario: "Arábia Saudita", resultado: "4 x 0" },
      { fase: "Grupo", adversario: "Dinamarca", resultado: "2 x 1" },
      { fase: "Oitavas", adversario: "Paraguai", resultado: "1 x 0 (gol de ouro)" },
      { fase: "Quartas", adversario: "Itália", resultado: "0 x 0 (4x3 pên.)" },
      { fase: "Semifinal", adversario: "Croácia", resultado: "2 x 1" },
      { fase: "Final", adversario: "Brasil", resultado: "3 x 0" },
    ]},
    vice: { nome: "Brasil", bandeira: "🇧🇷", jogos: 7, vitorias: 4, empates: 1, derrotas: 2, golsPro: 14, golsContra: 10, trajetoria: [
      { fase: "Grupo", adversario: "Escócia", resultado: "2 x 1" },
      { fase: "Grupo", adversario: "Marrocos", resultado: "3 x 0" },
      { fase: "Grupo", adversario: "Noruega", resultado: "1 x 2" },
      { fase: "Oitavas", adversario: "Chile", resultado: "4 x 1" },
      { fase: "Quartas", adversario: "Dinamarca", resultado: "3 x 2" },
      { fase: "Semifinal", adversario: "Holanda", resultado: "1 x 1 (4x2 pên.)" },
      { fase: "Final", adversario: "França", resultado: "0 x 3" },
    ]},
    mascote: "Footix",
    curiosidades: ["Zidane marcou 2 gols de cabeça na final", "Primeiro título francês, em casa"],
  },
  {
    ano: 2002, sede: "Coreia do Sul e Japão", sedeBandeira: "🇰🇷🇯🇵",
    artilheiro: "Ronaldo (Brasil) – 8 gols",
    campeao: { nome: "Brasil", bandeira: "🇧🇷", jogos: 7, vitorias: 7, empates: 0, derrotas: 0, golsPro: 18, golsContra: 4, trajetoria: [
      { fase: "Grupo", adversario: "Turquia", resultado: "2 x 1" },
      { fase: "Grupo", adversario: "China", resultado: "4 x 0" },
      { fase: "Grupo", adversario: "Costa Rica", resultado: "5 x 2" },
      { fase: "Oitavas", adversario: "Bélgica", resultado: "2 x 0" },
      { fase: "Quartas", adversario: "Inglaterra", resultado: "2 x 1" },
      { fase: "Semifinal", adversario: "Turquia", resultado: "1 x 0" },
      { fase: "Final", adversario: "Alemanha", resultado: "2 x 0" },
    ]},
    vice: { nome: "Alemanha", bandeira: "🇩🇪", jogos: 7, vitorias: 5, empates: 1, derrotas: 1, golsPro: 13, golsContra: 3, trajetoria: [
      { fase: "Grupo", adversario: "Arábia Saudita", resultado: "8 x 0" },
      { fase: "Grupo", adversario: "Irlanda", resultado: "1 x 1" },
      { fase: "Grupo", adversario: "Camarões", resultado: "2 x 0" },
      { fase: "Oitavas", adversario: "Paraguai", resultado: "1 x 0" },
      { fase: "Quartas", adversario: "Estados Unidos", resultado: "1 x 0" },
      { fase: "Semifinal", adversario: "Coreia do Sul", resultado: "1 x 0" },
      { fase: "Final", adversario: "Brasil", resultado: "0 x 2" },
    ]},
    mascote: "Ato, Kaz e Nik",
    curiosidades: ["Pentacampeonato brasileiro com 100% de aproveitamento", "Ronaldo voltou de lesões e foi decisivo"],
  },
  {
    ano: 2006, sede: "Alemanha", sedeBandeira: "🇩🇪",
    artilheiro: "Miroslav Klose (Alemanha) – 5 gols",
    campeao: { nome: "Itália", bandeira: "🇮🇹", jogos: 7, vitorias: 5, empates: 2, derrotas: 0, golsPro: 12, golsContra: 2, trajetoria: [
      { fase: "Grupo", adversario: "Gana", resultado: "2 x 0" },
      { fase: "Grupo", adversario: "Estados Unidos", resultado: "1 x 1" },
      { fase: "Grupo", adversario: "República Tcheca", resultado: "2 x 0" },
      { fase: "Oitavas", adversario: "Austrália", resultado: "1 x 0" },
      { fase: "Quartas", adversario: "Ucrânia", resultado: "3 x 0" },
      { fase: "Semifinal", adversario: "Alemanha", resultado: "2 x 0 (prorrog.)" },
      { fase: "Final", adversario: "França", resultado: "1 x 1 (5x3 pên.)" },
    ]},
    vice: { nome: "França", bandeira: "🇫🇷", jogos: 7, vitorias: 4, empates: 3, derrotas: 0, golsPro: 9, golsContra: 3, trajetoria: [
      { fase: "Grupo", adversario: "Suíça", resultado: "0 x 0" },
      { fase: "Grupo", adversario: "Coreia do Sul", resultado: "1 x 1" },
      { fase: "Grupo", adversario: "Togo", resultado: "2 x 0" },
      { fase: "Oitavas", adversario: "Espanha", resultado: "3 x 1" },
      { fase: "Quartas", adversario: "Brasil", resultado: "1 x 0" },
      { fase: "Semifinal", adversario: "Portugal", resultado: "1 x 0" },
      { fase: "Final", adversario: "Itália", resultado: "1 x 1 (3x5 pên.)" },
    ]},
    mascote: "Goleo",
    curiosidades: ["Cabeçada de Zidane em Materazzi", "Itália campeã invicta sofrendo só 2 gols"],
  },
  {
    ano: 2010, sede: "África do Sul", sedeBandeira: "🇿🇦",
    artilheiro: "Müller, Villa, Forlán e Sneijder – 5 gols",
    campeao: { nome: "Espanha", bandeira: "🇪🇸", jogos: 7, vitorias: 6, empates: 0, derrotas: 1, golsPro: 8, golsContra: 2, trajetoria: [
      { fase: "Grupo", adversario: "Suíça", resultado: "0 x 1" },
      { fase: "Grupo", adversario: "Honduras", resultado: "2 x 0" },
      { fase: "Grupo", adversario: "Chile", resultado: "2 x 1" },
      { fase: "Oitavas", adversario: "Portugal", resultado: "1 x 0" },
      { fase: "Quartas", adversario: "Paraguai", resultado: "1 x 0" },
      { fase: "Semifinal", adversario: "Alemanha", resultado: "1 x 0" },
      { fase: "Final", adversario: "Holanda", resultado: "1 x 0 (prorrog.)" },
    ]},
    vice: { nome: "Holanda", bandeira: "🇳🇱", jogos: 7, vitorias: 6, empates: 0, derrotas: 1, golsPro: 12, golsContra: 6, trajetoria: [
      { fase: "Grupo", adversario: "Dinamarca", resultado: "2 x 0" },
      { fase: "Grupo", adversario: "Japão", resultado: "1 x 0" },
      { fase: "Grupo", adversario: "Camarões", resultado: "2 x 1" },
      { fase: "Oitavas", adversario: "Eslováquia", resultado: "2 x 1" },
      { fase: "Quartas", adversario: "Brasil", resultado: "2 x 1" },
      { fase: "Semifinal", adversario: "Uruguai", resultado: "3 x 2" },
      { fase: "Final", adversario: "Espanha", resultado: "0 x 1 (prorrog.)" },
    ]},
    mascote: "Zakumi",
    curiosidades: ["Primeiro título da Espanha com o 'tiki-taka'", "Vuvuzelas dominaram os estádios"],
  },
  {
    ano: 2014, sede: "Brasil", sedeBandeira: "🇧🇷",
    artilheiro: "James Rodríguez (Colômbia) – 6 gols",
    melhorJogador: "Lionel Messi (Argentina)",
    melhorGoleiro: "Manuel Neuer (Alemanha)",
    campeao: { nome: "Alemanha", bandeira: "🇩🇪", jogos: 7, vitorias: 6, empates: 1, derrotas: 0, golsPro: 18, golsContra: 4, trajetoria: [
      { fase: "Grupo", adversario: "Portugal", resultado: "4 x 0" },
      { fase: "Grupo", adversario: "Gana", resultado: "2 x 2" },
      { fase: "Grupo", adversario: "Estados Unidos", resultado: "1 x 0" },
      { fase: "Oitavas", adversario: "Argélia", resultado: "2 x 1 (prorrog.)" },
      { fase: "Quartas", adversario: "França", resultado: "1 x 0" },
      { fase: "Semifinal", adversario: "Brasil", resultado: "7 x 1" },
      { fase: "Final", adversario: "Argentina", resultado: "1 x 0 (prorrog.)" },
    ]},
    vice: { nome: "Argentina", bandeira: "🇦🇷", jogos: 7, vitorias: 5, empates: 1, derrotas: 1, golsPro: 8, golsContra: 4, trajetoria: [
      { fase: "Grupo", adversario: "Bósnia e Herzegovina", resultado: "2 x 1" },
      { fase: "Grupo", adversario: "Irã", resultado: "1 x 0" },
      { fase: "Grupo", adversario: "Nigéria", resultado: "3 x 2" },
      { fase: "Oitavas", adversario: "Suíça", resultado: "1 x 0 (prorrog.)" },
      { fase: "Quartas", adversario: "Bélgica", resultado: "1 x 0" },
      { fase: "Semifinal", adversario: "Holanda", resultado: "0 x 0 (4x2 pên.)" },
      { fase: "Final", adversario: "Alemanha", resultado: "0 x 1 (prorrog.)" },
    ]},
    mascote: "Fuleco",
    curiosidades: ["Histórico 7x1 da Alemanha sobre o Brasil", "Götze decidiu na prorrogação"],
  },
  {
    ano: 2018, sede: "Rússia", sedeBandeira: "🇷🇺",
    artilheiro: "Harry Kane (Inglaterra) – 6 gols",
    melhorJogador: "Luka Modrić (Croácia)",
    melhorGoleiro: "Thibaut Courtois (Bélgica)",
    campeao: { nome: "França", bandeira: "🇫🇷", jogos: 7, vitorias: 6, empates: 1, derrotas: 0, golsPro: 14, golsContra: 6, trajetoria: [
      { fase: "Grupo", adversario: "Austrália", resultado: "2 x 1" },
      { fase: "Grupo", adversario: "Peru", resultado: "1 x 0" },
      { fase: "Grupo", adversario: "Dinamarca", resultado: "0 x 0" },
      { fase: "Oitavas", adversario: "Argentina", resultado: "4 x 3" },
      { fase: "Quartas", adversario: "Uruguai", resultado: "2 x 0" },
      { fase: "Semifinal", adversario: "Bélgica", resultado: "1 x 0" },
      { fase: "Final", adversario: "Croácia", resultado: "4 x 2" },
    ]},
    vice: { nome: "Croácia", bandeira: "🇭🇷", jogos: 7, vitorias: 4, empates: 2, derrotas: 1, golsPro: 14, golsContra: 9, trajetoria: [
      { fase: "Grupo", adversario: "Nigéria", resultado: "2 x 0" },
      { fase: "Grupo", adversario: "Argentina", resultado: "3 x 0" },
      { fase: "Grupo", adversario: "Islândia", resultado: "2 x 1" },
      { fase: "Oitavas", adversario: "Dinamarca", resultado: "1 x 1 (3x2 pên.)" },
      { fase: "Quartas", adversario: "Rússia", resultado: "2 x 2 (4x3 pên.)" },
      { fase: "Semifinal", adversario: "Inglaterra", resultado: "2 x 1 (prorrog.)" },
      { fase: "Final", adversario: "França", resultado: "2 x 4" },
    ]},
    mascote: "Zabivaka",
    curiosidades: ["Melhor campanha da história da Croácia", "Estreia do VAR em Copas"],
  },
  {
    ano: 2022, sede: "Catar", sedeBandeira: "🇶🇦",
    artilheiro: "Kylian Mbappé (França) – 8 gols",
    melhorJogador: "Lionel Messi (Argentina)",
    melhorGoleiro: "Emiliano Martínez (Argentina)",
    campeao: { nome: "Argentina", bandeira: "🇦🇷", jogos: 7, vitorias: 6, empates: 1, derrotas: 1, golsPro: 15, golsContra: 8, trajetoria: [
      { fase: "Grupo", adversario: "Arábia Saudita", resultado: "1 x 2" },
      { fase: "Grupo", adversario: "México", resultado: "2 x 0" },
      { fase: "Grupo", adversario: "Polônia", resultado: "2 x 0" },
      { fase: "Oitavas", adversario: "Austrália", resultado: "2 x 1" },
      { fase: "Quartas", adversario: "Holanda", resultado: "2 x 2 (4x3 pên.)" },
      { fase: "Semifinal", adversario: "Croácia", resultado: "3 x 0" },
      { fase: "Final", adversario: "França", resultado: "3 x 3 (4x2 pên.)" },
    ]},
    vice: { nome: "França", bandeira: "🇫🇷", jogos: 7, vitorias: 5, empates: 1, derrotas: 1, golsPro: 16, golsContra: 8, trajetoria: [
      { fase: "Grupo", adversario: "Austrália", resultado: "4 x 1" },
      { fase: "Grupo", adversario: "Dinamarca", resultado: "2 x 1" },
      { fase: "Grupo", adversario: "Tunísia", resultado: "0 x 1" },
      { fase: "Oitavas", adversario: "Polônia", resultado: "3 x 1" },
      { fase: "Quartas", adversario: "Inglaterra", resultado: "2 x 1" },
      { fase: "Semifinal", adversario: "Marrocos", resultado: "2 x 0" },
      { fase: "Final", adversario: "Argentina", resultado: "3 x 3 (2x4 pên.)" },
    ]},
    mascote: "La'eeb",
    curiosidades: ["Argentina perdeu na estreia e virou campeã", "Final considerada uma das melhores da história", "Messi conquistou seu primeiro título mundial"],
  },
];

export const titulos = [
  { selecao: "🇧🇷 Brasil", titulos: 5 },
  { selecao: "🇩🇪 Alemanha", titulos: 4 },
  { selecao: "🇮🇹 Itália", titulos: 4 },
  { selecao: "🇦🇷 Argentina", titulos: 3 },
  { selecao: "🇫🇷 França", titulos: 2 },
  { selecao: "🇺🇾 Uruguai", titulos: 2 },
  { selecao: "🏴󠁧󠁢󠁥󠁮󠁧󠁿 Inglaterra", titulos: 1 },
  { selecao: "🇪🇸 Espanha", titulos: 1 },
];

export const artilheirosHistoria = [
  { jogador: "Miroslav Klose", pais: "🇩🇪 Alemanha", gols: 16 },
  { jogador: "Ronaldo", pais: "🇧🇷 Brasil", gols: 15 },
  { jogador: "Gerd Müller", pais: "🇩🇪 Alemanha", gols: 14 },
  { jogador: "Just Fontaine", pais: "🇫🇷 França", gols: 13 },
  { jogador: "Lionel Messi", pais: "🇦🇷 Argentina", gols: 13 },
  { jogador: "Pelé", pais: "🇧🇷 Brasil", gols: 12 },
  { jogador: "Kylian Mbappé", pais: "🇫🇷 França", gols: 12 },
];

export const quiz = [
  { q: "Quem venceu a primeira Copa do Mundo, em 1930?", a: ["Argentina", "Uruguai", "Brasil", "Itália"], correct: 1 },
  { q: "Qual seleção venceu a Copa de 2002 com 100% de aproveitamento?", a: ["Alemanha", "França", "Brasil", "Itália"], correct: 2 },
  { q: "Quem é o maior artilheiro da história das Copas?", a: ["Pelé", "Ronaldo", "Klose", "Müller"], correct: 2 },
  { q: "Em qual Copa ocorreu o histórico 7x1?", a: ["2010", "2014", "2018", "2022"], correct: 1 },
  { q: "Quem marcou o 'Gol do Século' em 1986?", a: ["Pelé", "Maradona", "Zidane", "Messi"], correct: 1 },
  { q: "Qual país sediou a Copa de 2022?", a: ["Rússia", "Brasil", "Catar", "EUA"], correct: 2 },
  { q: "Qual jogador foi artilheiro com 13 gols em 1958?", a: ["Pelé", "Just Fontaine", "Garrincha", "Eusébio"], correct: 1 },
  { q: "Quantos títulos mundiais o Brasil tem?", a: ["3", "4", "5", "6"], correct: 2 },
];
